# Generated by Django 2.0.3 on 2018-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181203_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
