# Generated by Django 2.0.3 on 2018-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20181130_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
