# Generated by Django 2.0.3 on 2018-12-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_auto_20181130_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='question',
            name='username',
        ),
    ]
