# Generated by Django 2.0.3 on 2018-12-07 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 8), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 8), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('r', 'Resolved')], default='p', help_text='Status of Question Asked', max_length=1),
        ),
    ]
